server.port=8081

spring.application.name=account-service

custom.message=Ok you are LTM< employee


spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.bank.account_service=DEBUG
logging.pattern.level=%5p [%X{service},%X{correlationId}]

#management.endpoints.web.exposure.include=*

#Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

#Feign TimeOut Config
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

#Circuit Breaker
resilience4j.circuitbreaker.instances.orderService.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderService.sliding-window-size=5

#Timeout
resilience4j.circuitbreaker.instances.orderService.timeoutDuration=5s
resilience4j.circuitbreaker.instances.orderService.cancelRunningFuture=true
