server.port=8082
spring.application.name=order-service
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

logging.level.root=INFO
logging.level.com.bank.account_service=DEBUG
logging.pattern.level=%5p [%X{service},%X{correlationId}]